"""Add vendor_profile_weights table

Revision ID: 01b7bf3424a7
Revises: 20f3ca9ec397
Create Date: 2026-05-20 19:27:34.318843+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01b7bf3424a7'
down_revision: Union[str, None] = '20f3ca9ec397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_profile_weights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_profile_id', sa.UUID(), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('weight_domain', sa.Float(), nullable=False),
    sa.Column('weight_geography', sa.Float(), nullable=False),
    sa.Column('weight_financial', sa.Float(), nullable=False),
    sa.Column('weight_experience', sa.Float(), nullable=False),
    sa.Column('weight_certification', sa.Float(), nullable=False),
    sa.Column('weight_semantic', sa.Float(), nullable=False),
    sa.Column('weight_confidence', sa.Float(), nullable=False),
    sa.Column('total_feedback_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_vendor_profile_weights_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_profile_id'], ['vendor_profiles.id'], name=op.f('fk_vendor_profile_weights_vendor_profile_id_vendor_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_profile_weights'))
    )
    op.create_index(op.f('ix_vendor_profile_weights_org_id'), 'vendor_profile_weights', ['org_id'], unique=False)
    op.create_index(op.f('ix_vendor_profile_weights_vendor_profile_id'), 'vendor_profile_weights', ['vendor_profile_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_profile_weights_vendor_profile_id'), table_name='vendor_profile_weights')
    op.drop_index(op.f('ix_vendor_profile_weights_org_id'), table_name='vendor_profile_weights')
    op.drop_table('vendor_profile_weights')
    # ### end Alembic commands ###
