"""Initial Polyglot Schema

Revision ID: 20f3ca9ec397
Revises: 7535df344c80
Create Date: 2026-05-16 09:56:21.231940+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20f3ca9ec397'
down_revision: Union[str, None] = '7535df344c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenders', 'mongo_id',
               existing_type=sa.VARCHAR(length=24),
               nullable=False)
    op.alter_column('tenders', 'summary',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('vendor_profiles', sa.Column('vendor_id', sa.String(length=20), nullable=False))
    op.add_column('vendor_profiles', sa.Column('profile_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('vendor_profiles', sa.Column('profile_version', sa.Integer(), nullable=False))
    op.add_column('vendor_profiles', sa.Column('profile_completeness_pct', sa.Float(), nullable=False))
    op.add_column('vendor_profiles', sa.Column('completeness_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('vendor_profiles', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('vendor_profiles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('vendor_profiles', 'org_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('vendor_profiles', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('vendor_profiles', 'business_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_vendor_profiles_mongo_id'), table_name='vendor_profiles')
    op.create_index(op.f('ix_vendor_profiles_business_name'), 'vendor_profiles', ['business_name'], unique=False)
    op.create_index(op.f('ix_vendor_profiles_vendor_id'), 'vendor_profiles', ['vendor_id'], unique=True)
    op.drop_constraint(op.f('fk_vendor_profiles_user_id_users'), 'vendor_profiles', type_='foreignkey')
    op.drop_constraint(op.f('fk_vendor_profiles_org_id_organizations'), 'vendor_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_vendor_profiles_org_id_organizations'), 'vendor_profiles', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_vendor_profiles_user_id_users'), 'vendor_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('vendor_profiles', 'mongo_id')
    op.drop_column('vendor_profiles', 'metadata_fields')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_profiles', sa.Column('metadata_fields', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('vendor_profiles', sa.Column('mongo_id', sa.VARCHAR(length=24), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_vendor_profiles_user_id_users'), 'vendor_profiles', type_='foreignkey')
    op.drop_constraint(op.f('fk_vendor_profiles_org_id_organizations'), 'vendor_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_vendor_profiles_org_id_organizations'), 'vendor_profiles', 'organizations', ['org_id'], ['id'])
    op.create_foreign_key(op.f('fk_vendor_profiles_user_id_users'), 'vendor_profiles', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_vendor_profiles_vendor_id'), table_name='vendor_profiles')
    op.drop_index(op.f('ix_vendor_profiles_business_name'), table_name='vendor_profiles')
    op.create_index(op.f('ix_vendor_profiles_mongo_id'), 'vendor_profiles', ['mongo_id'], unique=True)
    op.alter_column('vendor_profiles', 'business_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('vendor_profiles', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('vendor_profiles', 'org_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('vendor_profiles', 'updated_at')
    op.drop_column('vendor_profiles', 'is_active')
    op.drop_column('vendor_profiles', 'completeness_details')
    op.drop_column('vendor_profiles', 'profile_completeness_pct')
    op.drop_column('vendor_profiles', 'profile_version')
    op.drop_column('vendor_profiles', 'profile_data')
    op.drop_column('vendor_profiles', 'vendor_id')
    op.alter_column('tenders', 'summary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('tenders', 'mongo_id',
               existing_type=sa.VARCHAR(length=24),
               nullable=True)
    # ### end Alembic commands ###
