"""Add vector tables for Phase 3

Revision ID: 7535df344c80
Revises: 001
Create Date: 2026-05-13 22:42:59.355585+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '7535df344c80'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mongo_id', sa.String(length=24), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_tenders_org_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenders'))
    )
    op.create_index(op.f('ix_tenders_mongo_id'), 'tenders', ['mongo_id'], unique=True)
    op.create_index(op.f('ix_tenders_org_id'), 'tenders', ['org_id'], unique=False)
    op.create_table('vendor_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mongo_id', sa.String(length=24), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('metadata_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_vendor_profiles_org_id_organizations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_vendor_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_profiles'))
    )
    op.create_index(op.f('ix_vendor_profiles_mongo_id'), 'vendor_profiles', ['mongo_id'], unique=True)
    op.create_index(op.f('ix_vendor_profiles_org_id'), 'vendor_profiles', ['org_id'], unique=False)
    op.create_index(op.f('ix_vendor_profiles_user_id'), 'vendor_profiles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_profiles_user_id'), table_name='vendor_profiles')
    op.drop_index(op.f('ix_vendor_profiles_org_id'), table_name='vendor_profiles')
    op.drop_index(op.f('ix_vendor_profiles_mongo_id'), table_name='vendor_profiles')
    op.drop_table('vendor_profiles')
    op.drop_index(op.f('ix_tenders_org_id'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_mongo_id'), table_name='tenders')
    op.drop_table('tenders')
    # ### end Alembic commands ###
